site_name: Prometheus Documentation
site_url: https://thecontrappostoshop.github.io/Documentation/
repo_url: https://github.com/TheContrappostoShop/Prometheus-MSLA
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/GFUn9gwRsj
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/623237352174055/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@thecontrappostoshop3787/
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - md_in_html